
(function () {
var scripts = [{"deps":{"./assets/TestSpine":1,"./assets/Scripts/EffectManager":2,"./assets/Guide/Guide":6,"./assets/Scripts/ActionController":7,"./assets/Scripts/Other/FishSwim":10,"./assets/Scripts/Loading/Loading":11,"./assets/Scripts/BundleManager":13,"./assets/Scripts/EventManager":15,"./assets/Scripts/FBInstantManager":20,"./assets/Scripts/LevelController":21,"./assets/Scripts/OptimizePageView":23,"./assets/Scripts/OptionController":24,"./assets/Scripts/Notification":26,"./assets/Scripts/spine":27,"./assets/Scripts/ListLevel/ClickItem":29,"./assets/Scripts/ListLevel/NewClickItem":30,"./assets/Scripts/Alert":31,"./assets/Scripts/UIController":4,"./assets/Scripts/ListLevel/ListLevel":3,"./assets/Introduce/Introduce":5,"./assets/Scripts/GameManager":8,"./assets/ComingSoon/ComingSoon2":9,"./assets/Scripts/Data":14,"./assets/Scripts/ButtonNext":12,"./assets/Scripts/ClipController":16,"./assets/Scripts/HomeController":19,"./assets/Scripts/CountDown5s":17,"./assets/Scripts/ComingSoon":18,"./assets/Scripts/LevelBase":22,"./assets/Scripts/Setting":25,"./assets/Scripts/StageController":28,"./assets/Levels/Level19/Script/Level19_1":32,"./assets/Levels/Level19/Script/Level19_2":33,"./assets/Levels/Level19/Script/Level19_3":34},"path":"preview-scripts/__qc_index__.js"},{"deps":{},"path":"preview-scripts/assets/TestSpine.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/EffectManager.js"},{"deps":{"../EffectManager":2,"./NewClickItem":30,"../Data":14},"path":"preview-scripts/assets/Scripts/ListLevel/ListLevel.js"},{"deps":{"./EffectManager":2,"./BundleManager":13,"./Data":14},"path":"preview-scripts/assets/Scripts/UIController.js"},{"deps":{"../Scripts/EffectManager":2},"path":"preview-scripts/assets/Introduce/Introduce.js"},{"deps":{},"path":"preview-scripts/assets/Guide/Guide.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/ActionController.js"},{"deps":{"./Data":14,"./EffectManager":2,"./FBInstantManager":20,"./BundleManager":13},"path":"preview-scripts/assets/Scripts/GameManager.js"},{"deps":{"../Scripts/ComingSoon":18},"path":"preview-scripts/assets/ComingSoon/ComingSoon2.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/Other/FishSwim.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/Loading/Loading.js"},{"deps":{"./EffectManager":2},"path":"preview-scripts/assets/Scripts/ButtonNext.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/BundleManager.js"},{"deps":{"./FBInstantManager":20},"path":"preview-scripts/assets/Scripts/Data.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/EventManager.js"},{"deps":{"./StageController":28,"./EffectManager":2},"path":"preview-scripts/assets/Scripts/ClipController.js"},{"deps":{"./EventManager":15},"path":"preview-scripts/assets/Scripts/CountDown5s.js"},{"deps":{"./Data":14},"path":"preview-scripts/assets/Scripts/ComingSoon.js"},{"deps":{"./Data":14},"path":"preview-scripts/assets/Scripts/HomeController.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/FBInstantManager.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/LevelController.js"},{"deps":{"./EffectManager":2,"./Data":14,"./EventManager":15,"./GameManager":8,"./BundleManager":13},"path":"preview-scripts/assets/Scripts/LevelBase.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/OptimizePageView.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/OptionController.js"},{"deps":{"./Data":14},"path":"preview-scripts/assets/Scripts/Setting.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/Notification.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/spine.js"},{"deps":{"./EffectManager":2},"path":"preview-scripts/assets/Scripts/StageController.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/ListLevel/ClickItem.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/ListLevel/NewClickItem.js"},{"deps":{},"path":"preview-scripts/assets/Scripts/Alert.js"},{"deps":{"../../../Scripts/LevelBase":22},"path":"preview-scripts/assets/Levels/Level19/Script/Level19_1.js"},{"deps":{"../../../Scripts/LevelBase":22},"path":"preview-scripts/assets/Levels/Level19/Script/Level19_2.js"},{"deps":{"../../../Scripts/LevelBase":22},"path":"preview-scripts/assets/Levels/Level19/Script/Level19_3.js"}];
var entries = ["preview-scripts/__qc_index__.js"];
var bundleScript = 'preview-scripts/__qc_bundle__.js';

/**
 * Notice: This file can not use ES6 (for IE 11)
 */
var modules = {};
var name2path = {};

// Will generated by module.js plugin
// var scripts = ${scripts};
// var entries = ${entries};
// var bundleScript = ${bundleScript};

if (typeof global === 'undefined') {
    window.global = window;
}

var isJSB = typeof jsb !== 'undefined';

function getXMLHttpRequest () {
    return window.XMLHttpRequest ? new window.XMLHttpRequest() : new ActiveXObject('MSXML2.XMLHTTP');
}

function downloadText(url, callback) {
    if (isJSB) {
        var result = jsb.fileUtils.getStringFromFile(url);
        callback(null, result);
        return;
    }

    var xhr = getXMLHttpRequest(),
        errInfo = 'Load text file failed: ' + url;
    xhr.open('GET', url, true);
    if (xhr.overrideMimeType) xhr.overrideMimeType('text\/plain; charset=utf-8');
    xhr.onload = function () {
        if (xhr.readyState === 4) {
            if (xhr.status === 200 || xhr.status === 0) {
                callback(null, xhr.responseText);
            }
            else {
                callback({status:xhr.status, errorMessage:errInfo + ', status: ' + xhr.status});
            }
        }
        else {
            callback({status:xhr.status, errorMessage:errInfo + '(wrong readyState)'});
        }
    };
    xhr.onerror = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(error)'});
    };
    xhr.ontimeout = function(){
        callback({status:xhr.status, errorMessage:errInfo + '(time out)'});
    };
    xhr.send(null);
};

function loadScript (src, cb) {
    if (typeof require !== 'undefined') {
        require(src);
        return cb();
    }

    // var timer = 'load ' + src;
    // console.time(timer);

    var scriptElement = document.createElement('script');

    function done() {
        // console.timeEnd(timer);
        // deallocation immediate whatever
        scriptElement.remove();
    }

    scriptElement.onload = function () {
        done();
        cb();
    };
    scriptElement.onerror = function () {
        done();
        var error = 'Failed to load ' + src;
        console.error(error);
        cb(new Error(error));
    };
    scriptElement.setAttribute('type','text/javascript');
    scriptElement.setAttribute('charset', 'utf-8');
    scriptElement.setAttribute('src', src);

    document.head.appendChild(scriptElement);
}

function loadScripts (srcs, cb) {
    var n = srcs.length;

    srcs.forEach(function (src) {
        loadScript(src, function () {
            n--;
            if (n === 0) {
                cb();
            }
        });
    })
}

function formatPath (path) {
    let destPath = window.__quick_compile_project__.destPath;
    if (destPath) {
        let prefix = 'preview-scripts';
        if (destPath[destPath.length - 1] === '/') {
            prefix += '/';
        }
        path = path.replace(prefix, destPath);
    }
    return path;
}

window.__quick_compile_project__ = {
    destPath: '',

    registerModule: function (path, module) {
        path = formatPath(path);
        modules[path].module = module;
    },

    registerModuleFunc: function (path, func) {
        path = formatPath(path);
        modules[path].func = func;

        var sections = path.split('/');
        var name = sections[sections.length - 1];
        name = name.replace(/\.(?:js|ts|json)$/i, '');
        name2path[name] = path;
    },

    require: function (request, path) {
        var m, requestScript;

        path = formatPath(path);
        if (path) {
            m = modules[path];
            if (!m) {
                console.warn('Can not find module for path : ' + path);
                return null;
            }
        }

        if (m) {
            let depIndex = m.deps[request];
            // dependence script was excluded
            if (depIndex === -1) {
                return null;
            }
            else {
                requestScript = scripts[ m.deps[request] ];
            }
        }
        
        let requestPath = '';
        if (!requestScript) {
            // search from name2path when request is a dynamic module name
            if (/^[\w- .]*$/.test(request)) {
                requestPath = name2path[request];
            }

            if (!requestPath) {
                if (CC_JSB) {
                    return require(request);
                }
                else {
                    console.warn('Can not find deps [' + request + '] for path : ' + path);
                    return null;
                }
            }
        }
        else {
            requestPath = formatPath(requestScript.path);
        }

        let requestModule = modules[requestPath];
        if (!requestModule) {
            console.warn('Can not find request module for path : ' + requestPath);
            return null;
        }

        if (!requestModule.module && requestModule.func) {
            requestModule.func();
        }

        if (!requestModule.module) {
            console.warn('Can not find requestModule.module for path : ' + path);
            return null;
        }

        return requestModule.module.exports;
    },

    run: function () {
        entries.forEach(function (entry) {
            entry = formatPath(entry);
            var module = modules[entry];
            if (!module.module) {
                module.func();
            }
        });
    },

    load: function (cb) {
        var self = this;

        var srcs = scripts.map(function (script) {
            var path = formatPath(script.path);
            modules[path] = script;

            if (script.mtime) {
                path += ("?mtime=" + script.mtime);
            }
            return path;
        });

        console.time && console.time('load __quick_compile_project__');
        // jsb can not analysis sourcemap, so keep separate files.
        if (bundleScript && !isJSB) {
            downloadText(formatPath(bundleScript), function (err, bundleSource) {
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                if (err) {
                    console.error(err);
                    return;
                }

                let evalTime = 'eval __quick_compile_project__ : ' + srcs.length + ' files';
                console.time && console.time(evalTime);
                var sources = bundleSource.split('\n//------QC-SOURCE-SPLIT------\n');
                for (var i = 0; i < sources.length; i++) {
                    if (sources[i]) {
                        window.eval(sources[i]);
                        // not sure why new Function cannot set breakpoints precisely
                        // new Function(sources[i])()
                    }
                }
                self.run();
                console.timeEnd && console.timeEnd(evalTime);
                cb();
            })
        }
        else {
            loadScripts(srcs, function () {
                self.run();
                console.timeEnd && console.timeEnd('load __quick_compile_project__');
                cb();
            });
        }
    }
};

// Polyfill for IE 11
if (!('remove' in Element.prototype)) {
    Element.prototype.remove = function () {
        if (this.parentNode) {
            this.parentNode.removeChild(this);
        }
    };
}
})();
    